### ISSUE TITLE
New logo for SecureStore

### ISSUE THREAD

**Issue by reallinfo** [neosmart/SecureStore#1]
I wanted to contribute to SecureStore. I designed a logo for SecureStore. If you like it, I'll send you the files.

![securestore](https://user-images.githubusercontent.com/36298335/37907609-4add1896-310e-11e8-8864-95f23daf0274.jpg)

**Comment by mqudsi** [comment]
I appreciate [your logo for unicode.net](https://github.com/neosmart/unicode.net/issues/2) but for SecureStore we're going to be sticking to the image we are currently using:

https://neosmart.net/blog/2017/securestore-a-net-secrets-manager/

Thank you!
