### ISSUE TITLE
Can you provide Strong Name assembly in Visual Studio Nugget Package? 

### ISSUE THREAD

**Issue by sameerpanse** [neosmart/SecureStore#13]
Can you provide Strong Name assembly in Visual Studio Nugget Package?

**Comment by mqudsi** [comment]
We can definitely do that! Let me add an snk and push out an update.

**Comment by mqudsi** [comment]
Sorry for the delay, but I've just published SecureStore 1.2.0 to NuGet with a strongly-signed `NeoSmart.SecureStore.dll`.

As with other open source projects, the SNK is not private; it has been published alongside the project to the repo and should only be used to assume unique identification of the binary and not for trusted signer purposes.

NuGet link (will be live when NuGet updates): https://www.nuget.org/packages/SecureStore/1.2.0

**Comment by sameerpanse** [comment]
Thanks for providing an update!
