### ISSUE TITLE
How to set Connection string with the CLI

### ISSUE THREAD

**Issue by Camelxx** [neosmart/SecureStore#14]
Trying to set a connection string with the cli but only getting this error back.

Expected a single "key=value" or "key" "value" to set!

SecureStore --store secrets.json set sonnectionString Server=localhost;Database=bleh -k secrets.key

 Tried setting it like SecureStore --store secrets.json set sonnectionString 'connectiong string' -k secrets.key

SecureStore --store secrets.json set sonnectionString "connectiong string" -k secrets.key

The issue is the connection string contains = and think the cli don't like it

How to add it ?

**Comment by mqudsi** [comment]
Use the interactive mode, with `SecureStore -k secrets.key set connectionString <ENTER>`

**Comment by mqudsi** [comment]
I don't know what shell you are using, but usually the bigger issue is the `;` and not the `=`

**Comment by Camelxx** [comment]
Thank you will try the inreractive mode , and using normal cmd

**Comment by babskig** [comment]
You need to use the other format (key=value) and quote the arguments to prevent the shell from interpreting the ; as a command separator.

I used:
SecureStore --store secrets.json set 'sonnectionString=Server=localhost;Database=bleh' -k secrets.key

**Comment by mqudsi** [comment]
I did not properly understand this bug report at the time it was filed, but this is a duplicate of #18 which has been fixed and will be in the next release.

**Comment by mqudsi** [comment]
I did not properly understand this bug report at the time it was filed, but this is a duplicate of https://github.com/neosmart/SecureStore/issues/18 which has been fixed and will be in the next release.
