### ISSUE TITLE
LoadKeyFromStream doesn't work

### ISSUE THREAD

**Issue by ae-vivanov** [neosmart/SecureStore#16]
Hey guys, 
I'm trying to load a secrets key file from stream, but it always fails with `InvalidKeyFileException`.  I spend some time on debugging and found that when you copy the input stream in `LoadKeyFromStream`  method, you don't reset the position and `PemReader` is the local memory stream. 
Do you guys accept pull requests, is there guidelines for your team or should I wait when you fix it yourself?

**Comment by mqudsi** [comment]
Sorry you ran into an issue with the library! This should definitely be included in the unit tests.
I'm happy to take a PR from you if you can open one.

**Comment by mqudsi** [comment]
I just pushed out version 1.2.1 to nuget with your fix. Thank you very much! https://www.nuget.org/packages/SecureStore
